### ISSUE TITLE
Sensor not sending smooth values

### ISSUE THREAD

**Issue by uzaymuh** [WorldFamousElectronics/PulseSensorPlayground#105]
Hello,
So I connected my sensor and uploaded the Getting Started sketch. But as you can see I'm not getting a smooth chart, so Icannot set a threshold and calculate BPM.

![image](https://user-images.githubusercontent.com/37838975/62298042-e86d5580-b47a-11e9-89d3-76b16a97009e.png)

BTW, I once got a smooth chart and it was working, but now it's not.

**Comment by biomurph** [comment]
@uzaymuh I need some more information to help solve your problem. What Arduino board are you using? Can you send a picture of your setup so I can verify your Pulse Sensor is legit?

Also, by looking at your signal I think you might be experiencing power line noise. Are you on a laptop that is plugged into the wall? That can be an issue sometimes with some computer power supplies. If this is the issue and you need to be plugged in, it's best to make sure that the Pulse Sensor has some power conditioning. A simple way to do this is to run it from the 3.3V power output on the Arduino (assuming you are using an UNO).
