### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by evertonab28** [WorldFamousElectronics/PulseSensorPlayground#106]
I am a teacher in Brazil, I am developing a compilation of scripts with Arduino educational practices, aimed at teachers without knowledge of Arduino and electronics. I would like to know if you allow me to translate the sketch provided by you, keeping the references and credits to you. Thank you!

**Comment by biomurph** [comment]
@evertonab28 
That sounds great!
All of our code is open-sourced, so you have full rights to use, copy, modify, etc. so long as you attribute to us as the original makers. 
Please let us know when you have something complete as we would love to promote it!
