### ISSUE TITLE
High value readings when I have almost anything else in my code.

### ISSUE THREAD

**Issue by kathblair** [WorldFamousElectronics/PulseSensorPlayground#108]
Hi - I'm trying to use the pulse sensor with a couple of other sensors and some outputs, but it seems like -- even though I am using the interrupts -- if there's anything much in the loop itself, I get very high readings. I had commented out the section reading the GSR sensor and the temp sensor and got reasonable readings, but as soon as I added it back in, they went very high again - I could see it go from 60-70 to 90 when I added additional code. Any thoughts as to what's going on? I was using it on a seeeduino lotus.

`#include <math.h>
#define USE_ARDUINO_INTERRUPTS true    // Set-up low-level interrupts for most acurate BPM math.
#include <PulseSensorPlayground.h>     // Includes the PulseSensorPlayground Library.   

//  Variables
const int PulseWire = A0;       // PulseSensor PURPLE WIRE connected to ANALOG PIN 0
const int LED13 = 13;          // The on-board Arduino LED, close to PIN 13.
int Threshold = 550;           // Determine which Signal to "count as a beat" and which to ignore.
// Use the "Gettting Started Project" to fine-tune Threshold Value beyond default setting.
// Otherwise leave the default "550" value.
int myBPM;

PulseSensorPlayground pulseSensor;  // Creates an instance of the PulseSensorPlayground object called "pulseSensor"

const int GSR = A2;
int sensorValue = 0;
int gsr_average = 0;
long gsr_timer = 0;
int gsr_reading_int = 5; //in millis
int gsr_counter = 0;
long gsr_sum = 0;

//temp sensor stuff
const int B = 4275;               // B value of the thermistor
const int R0 = 100000;            // R0 = 100k
const int pinTempSensor = A6;     // Grove - Temperature Sensor connect to A0
int curtempreading = 0;

//other vars
long printtimer = 0;
int printinterval = 1000;
long loopmillis = 0;

void setup() {
  Serial.begin(9600);

  // Configure the PulseSensor object, by assigning our variables to it.
  pulseSensor.analogInput(PulseWire);
  pulseSensor.blinkOnPulse(LED13);       //auto-magically blink Arduino's LED with heartbeat.
  pulseSensor.setThreshold(Threshold);

  // Double-check the "pulseSensor" object was created and "began" seeing a signal.
  if (pulseSensor.begin()) {
    Serial.println("We created a pulseSensor Object !");  //This prints one time at Arduino power-up,  or on Arduino reset.
  }
}

void loop() {
  loopmillis = millis(); // so I only need to do it once per loop, I guess?
  // Heart Rate
  myBPM = pulseSensor.getBeatsPerMinute();  // Calls function on our pulseSensor object that returns BPM as an "int".
  // "myBPM" hold this BPM value now.

/*
  if (pulseSensor.sawStartOfBeat()) {            // Constantly test to see if "a beat happened".
    Serial.println("♥  A HeartBeat Happened ! "); // If test is "true", print a message "a heartbeat happened".
    Serial.print("BPM: ");                        // Print phrase "BPM: "
    Serial.println(myBPM);                        // Print the value inside of myBPM.
  }*/
  
  //GSR values
  
  if (loopmillis > gsr_timer + gsr_reading_int) {
    gsr_timer = loopmillis;
    sensorValue = analogRead(GSR);
    gsr_sum += sensorValue;
    if (gsr_counter == 9) {
      gsr_counter = 0;
      gsr_average = gsr_sum / 10;
      //Serial.println(gsr_average);
      gsr_sum = 0;
    } else {
      gsr_counter++;
    }
    
  }

/*
  //Temp reading
  curtempreading = analogRead(pinTempSensor);

  float R = 1023.0 / curtempreading - 1.0;
  R = R0 * R;

  float temperature = 1.0 / (log(R / R0) / B + 1 / 298.15) - 273.15; // convert to temperature via datasheet

  //Serial.print("temperature = ");
  //Serial.println(temperature);
*/
  printinfo();

}

void printinfo() {
  if(millis()>printtimer+printinterval){
    printtimer = millis();
    Serial.println("GSR: " + String(gsr_average) + " BPM: " + String(myBPM));
  }
}
`

Any help is much appreciated, thanks!

**Comment by biomurph** [comment]
@kathblair 
Looking at your code, it seems that you are trying to measure the GSR sensor at a rate of 200Hz (every 5mS) is that right?
Also, it looks like when you comment out the temp code, you are measuring the temperature sensor  once every loop.

It's very possible that your GSR and Temp code is getting stepped on by the Pulse Sensor interrupt.

First, you probably don't need to sample the other sensors as often as you seem to be doing. both the temperature and gsr values will change rather slowly, and when you sample fast you get a lot of noise. 

If you insist on sampling those other sensors, you might want to try building off of the BPM_Alternative code example. That code uses a software timer to time the Pulse Sensor samples. Using that would mean that all of the analog reads that you do are initiated from the loop, and they won't be stepping on each other.

Please try that and reply back if it fixes the problem, then we'll know how to move forward. There are a couple tools in the interrupt driven code that could help if that's true.

Also, please send a pic of your hardware setup so I can verify your Pulse Sensor hardware
