### ISSUE TITLE
High value of IBI & BPM using PulseSensor_BPM_Alternative

### ISSUE THREAD

**Issue by Coting-ting** [WorldFamousElectronics/PulseSensorPlayground#124]
Dear PulseSensor Team,

> I download the zip the current version.

I am using **Arduino Nano 33 BLE** and **PulseSensor_BPM_Alternative** code. It is working for the serial plotter, but I get very high values in the serial monitor. Is there an explanation to get the correct values of BPM & IBI?

It's code(PulseSensor_BPM_Alternative) and screen shots of that.

![Image 4](https://user-images.githubusercontent.com/63554104/79075616-91689180-7d26-11ea-976c-41c43f401234.png)

![Image 5](https://user-images.githubusercontent.com/63554104/79075621-9af1f980-7d26-11ea-9209-7a696af10cf6.png)

![Image 1](https://user-images.githubusercontent.com/63554104/79075625-a34a3480-7d26-11ea-8483-9699c4822d7e.png)
The raw sensor data looks normally.

![Image 2](https://user-images.githubusercontent.com/63554104/79075630-a6ddbb80-7d26-11ea-99da-a5712f2e0c0a.png)
The BPM is too high.

![Image 3](https://user-images.githubusercontent.com/63554104/79075632-a9d8ac00-7d26-11ea-9e94-e67b4755912a.png)
The IBI is too high.

Thanks you.

**Comment by biomurph** [comment]
@Coting-ting 
That is an interesting pulse waveform that you're getting.
Can you tell me what sensor you are using? Post a picture of it?
