### ISSUE TITLE
get the BPM data

### ISSUE THREAD

**Issue by lucasroth** [WorldFamousElectronics/PulseSensorPlayground#127]
Hi, how can I get the value of the data plotted in the sample PulseSensor_BPM? can´t find documentation of the library´s functions.
Can I retrieve the BPM value, and do it without getting into the library .cpp files?

**Comment by biomurph** [comment]
@lucasroth 
What do you mean by 'get the data plotted in the sample'?

You can retrieve the BPM values easily by making simple modification to the example sketch.

**Comment by lucasroth** [comment]
hi, indeed realized about the functions available, just use: pulseSensor.getBeatsPerMinute()
by the way, I am using esp32, so changed the function of the mapping data for output:
`
void PulseSensor::readNextSample() {
  // We assume assigning to an int is atomic.
  Signal = map(analogRead(InputPin), 0, 4095, 0, 1023);
}`

the data received doesn´t seem to be near 550 is low as 450, and with low range between high and low levels, any advice on how this can be managed, or how to improve it?

**Comment by biomurph** [comment]
@lucasroth 
Instead of modifying the library, try setting the analog resolution
`analogReadResolution(10);`

Also, please send a picture of your Pulse Sensor so I can verify the hardware.

**Comment by lucasroth** [comment]
> @lucasroth
> Instead of modifying the library, try setting the analog resolution
> `analogReadResolution(10);`
> 
> Also, please send a picture of your Pulse Sensor so I can verify the hardware.

Hi, thanks for help! sorry for delay have been busy, here are the photos:
![sen1](https://user-images.githubusercontent.com/5168629/89141124-a2c1ed80-d511-11ea-9234-cc8988061654.png)
![sen2](https://user-images.githubusercontent.com/5168629/89141128-a5bcde00-d511-11ea-928a-a1d48411d156.png)

When using latest lib V1.5 the values go very high near 2000, then just adding analogReadResolution(10); the values drop to 450-500 range. The same happens modifying the lib on: void PulseSensor::readNextSample() { // We assume assigning to an int is atomic. Signal = map(analogRead(InputPin), 0, 4095, 0, 1023); }
![graf1](https://user-images.githubusercontent.com/5168629/89142871-95f3c880-d516-11ea-93b3-beb203792874.png)

Any advice to make it work using esp32 wroom?

**Comment by lucasroth** [comment]
![IMG_20200802_232356](https://user-images.githubusercontent.com/5168629/89143258-fafbee00-d517-11ea-863d-f14a2a89e788.jpg)
![IMG_20200802_232245-1](https://user-images.githubusercontent.com/5168629/89143260-fc2d1b00-d517-11ea-858d-29e36d077e30.jpg)
better photos

**Comment by biomurph** [comment]
Hi Lucas,

I can see by the phots that you have a knock-off Pulse Sensor. Since I don't know what is in that hardware, I really can't help you troubleshoot.
Please support the original makers of Open Source hardware and purchase only legit products.
You can find the Pulse Sensor at
www.pulsesensor.com
www.adafruit.com
www.sparkfun.com
www.mouser.com
www.digikey.com

You will likely get a better result when you get the real deal.
