### ISSUE TITLE
Extremely High Raw Sensor Values

### ISSUE THREAD

**Issue by sam-shridhar1950f** [WorldFamousElectronics/PulseSensorPlayground#139]
I am getting values over 900 consistently. This is a new product. I am using the "Getting Started" code from the playground. 
![image](https://user-images.githubusercontent.com/62958051/105644991-dea59200-5e66-11eb-8f63-a5218c83136e.png)
![image](https://user-images.githubusercontent.com/62958051/105645007-f9780680-5e66-11eb-9496-1590673acd5d.png)

![image](https://user-images.githubusercontent.com/62958051/105645048-3217e000-5e67-11eb-9f90-9c51bf010eee.png)

**Comment by ghost** [comment]
Was ist das ja ein Produkt

**Comment by sam-shridhar1950f** [comment]
> Was ist das ja ein Produkt
Yes, it is the Pulse sensor

**Comment by biomurph** [comment]
@sam-shridhar1950f 
That is some noise for sure.
 
Interesting that it is all at the high end of the ADC and the range of values is under 100 points. 
Can you tell me more about your setup? Your Pulse Sensor does look like it's legit, but it's super out of focus photo.

How do you have it connected? Do you have the clear vinyl sticker on the front of the sensor?

**Comment by sam-shridhar1950f** [comment]
@biomurph 

It is connected to an Arduino Uno with all the recommended connections (A0, 5V, GND). I am "goldilocks" pressing the sensor. Yes, I see the vinyl sticker.

**Comment by biomurph** [comment]
@sam-shridhar1950f 
When you are *not* touching the sensor, the signal should settle around V/2 and the ADC result should be somewhere about 500 counts. Do you find that is the case?
What kind of computer are you using? Are you plugged into a wall outlet? Sometimes Pulse Sensor can be susceptible to power line noise.

**Comment by sam-shridhar1950f** [comment]
@biomurph 

No. When I am not touching the sensor the values stay at the 900s-1000s. I am using a Microsoft Surface Book 3, and the arduino is connected via USB to the laptop.

**Comment by biomurph** [comment]
This does sound like something is wrong with the sensor. Can you dm me? Or email joel-at-pulsesensor-dot-com

**Comment by sam-shridhar1950f** [comment]
Sure, sent you a "hello" via email. @joelSensor
