### ISSUE TITLE
PulseSensor Playground downloaded by Arduino doesn't work properly for Arduino Nano 33 BLE

### ISSUE THREAD

**Issue by Leoriem-code** [WorldFamousElectronics/PulseSensorPlayground#142]
Don't know if that's where I should put it but here we go.
In interrupts.h, the line 272 and 318 are commented. A such, when we're not using an ATMega or an ATtiny, we receive an error.

Also, cli() and sei() are not declared (lines 72 and 73) and that also the cause of problems:

```
In file included from .\Arduino\libraries\PulseSensor_Playground\src/PulseSensorPlayground.h:439:0,
                 from .\Arduino\libraries\PulseSensor_Playground\src\PulseSensorPlayground.cpp:16:
.\Arduino\libraries\PulseSensor_Playground\src\PulseSensorPlayground.cpp: In member function 'boolean PulseSensorPlayground::sawNewSample()':
.\Arduino\libraries\PulseSensor_Playground\src/utility/Interrupts.h:72:41: error: 'cli' was not declared in this scope
 #define DISABLE_PULSE_SENSOR_INTERRUPTS cli()
                                         ^
.\Arduino\libraries\PulseSensor_Playground\src\PulseSensorPlayground.cpp:105:5: note: in expansion of macro 'DISABLE_PULSE_SENSOR_INTERRUPTS'
     DISABLE_PULSE_SENSOR_INTERRUPTS;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\Arduino\libraries\PulseSensor_Playground\src/utility/Interrupts.h:73:40: error: 'sei' was not declared in this scope
 #define ENABLE_PULSE_SENSOR_INTERRUPTS sei()
                                        ^
.\Arduino\libraries\PulseSensor_Playground\src\PulseSensorPlayground.cpp:108:5: note: in expansion of macro 'ENABLE_PULSE_SENSOR_INTERRUPTS'
     ENABLE_PULSE_SENSOR_INTERRUPTS;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using library PulseSensor_Playground at version 1.5.1 in folder: .\Arduino\libraries\PulseSensor_Playground 
exit status 1
Error compiling for board Arduino Nano 33 BLE.
```

**Comment by biomurph** [comment]
For the Arduino Nano 33 BLE, you need to use the PulseSensor_BPM_Alternative.ino example sketch

**Comment by Leoriem-code** [comment]
> 
> 
> For the Arduino Nano 33 BLE, you need to use the PulseSensor_BPM_Alternative.ino example sketch

Doesn't change anything. The problem is with the lines 72 and 73 where cli() and sei() are not declared.
I used PulseSensor_BPM_Alternative.ino without touching it (my wiring was already correct) and I get the error that I reported

**Comment by biomurph** [comment]
@Leoriem-code that is odd. I have just compiled the Alternative sketch for the Arduino Nano 33 BLE and I don't get the same error. 

Stand by

**Comment by biomurph** [comment]
Please delete the library that you have on your computer, and download the current version directly from this repository using the CODE button and selecting the Download ZIP option.

**Comment by Leoriem-code** [comment]
It has compiled correctly, thank you
