### ISSUE TITLE
Do we need to set THRESHOLD twice when we use 2 pulsesensors at once?

### ISSUE THREAD

**Issue by Lotushu** [WorldFamousElectronics/PulseSensorPlayground#152]
The code <TwoPulseSensors_On_OneArduino> sets threshold by using  pulseSensor.setThreshold(THRESHOLD). But I found out that it doesn't work for the second pulsesensor (pin A1, not A0). It continues to output data whatever threshold I set. So need I to use pulseSensor.setThreshold(THRESHOLD, 0) and pulseSensor.setThreshold(THRESHOLD, 1)  to set two thresholds separately?

**Comment by biomurph** [comment]
@Lotushu
Yes, you appear to be correct.
This is a bug in the multiple Pulse Sensor scenario.
I'll see what it will take to fix it.

**Comment by biomurph** [comment]
PulseSenor Playground Library supports multiple PulseSensors and each has it's own parameters to set.
