### ISSUE TITLE
GETTING STARTED WORKING BUT NOT GETTING BPM TO MONITOR

### ISSUE THREAD

**Issue by finntuberlin** [WorldFamousElectronics/PulseSensorPlayground#154]
Hello All,

When I run the getting started example sketch I can see a pulse signal in my serial plotter, which tells me my sensor is working, however, when I open the getting_bpm_to_monitor sketch, all I see is random inconsistent values that only show up if I lift my finger up and down quickly, otherwise if a keep my finger on the sensor no values are shown. I am using the goldilocks amount of pressure. I have also played around with the threshold value to no avail. The code hasn't been changed at all from the example, other than playing with the threshold value, but I have kept the threshold value within the recommended window. 

Using Arduino DUO, all ports are connected as shown in tutorial, as I said plotter is working in getting started, but not in get bpm.

Thank you

**Comment by biomurph** [comment]
@finntuberlin 
The problem you are having is straightforward.
The Serial Plotter in Arduino is expecting to receive some number, or a series of numbers, separated by a comma or a space or a tab, and terminating in a carriage return.
The Getting_BPM_to_Monitor.ino sketch is not doing that. If you look into the loop function, that sketch is sending human readable text that is not formatted to the Serial Plotter. The Serial Plotter is doing it's best to try and interpret the data, and that's why you're seeing all the crazy nonsense.

Instead, open up the Serial Monitor, and you will see what the sketch is sending.

**Comment by finntuberlin** [comment]
Hi Joel Thanks for the quick response,

I didn't express my question clearly enough. I am in fact looking at my serial monitor but all I am getting is the following

The one reading you are seeing there is the random values I get that only show up if I move my finger up and down. otherwise nothing happens
<img width="1512" alt="Screen Shot 2022-07-12 at 4 06 57 PM" src="https://user-images.githubusercontent.com/109156416/178509530-d8ef47ca-3412-4bc0-b82a-50a54e28e9e1.png">

**Comment by biomurph** [comment]
@finntuberlin 
Ah, OK. 
I think we need more information to chase down this issue.

- You say you are using Arduino DUO, but there is no Arduino DUO. Do you mean UNO or DUE?
- Can you add a screenshot of the Serial Plotter when running the Arduino_BPM sketch?
- Can you add a picture of your hardware setup including wired connections and Pulse Sensor?

**Comment by finntuberlin** [comment]
Yes I mean Arduino UNO sorry about the mixup. 

Not sure with Arduino_BPM if you meant a screen shot of the Getting_BPM_to_Monitor sketch (1st photo) or the Pulsesensor_BPM sketch (2nd photo) but here are screenshots from the Serial Plotter from both. Also attached is a photo of my setup.

<img width="1509" alt="Screen Shot 2022-07-12 at 4 25 51 PM" src="https://user-images.githubusercontent.com/109156416/178514399-3cbdee20-50b8-47c2-8f60-937ca7abba18.png">
<img width="1510" alt="Screen Shot 2022-07-12 at 4 21 40 PM" src="https://user-images.githubusercontent.com/109156416/178514430-f0dca03c-91b9-48c1-8f37-14028c0cbd84.png">

![IMG_1178](https://user-images.githubusercontent.com/109156416/178514852-4336072d-918a-4a20-a0d4-1bf51efc5f10.jpg)

**Comment by biomurph** [comment]
@finntuberlin 
I see the problem.
The sensor you are using is not our Pulse Sensor. It's clear from the picture of the hardware.
Also note in [this guide](https://pulsesensor.com/pages/getting-advanced) at the bottom there is a screen shot of the Serial Plotter. You should be seeing a very big pulse signal. The one you show is very small. 
I cannot troubleshoot hardware that I have not a clue what is on there.

Please support the original makers of Pulse Sensor by purchasing the legit product.
Our Pulse Sensor is available on our website, [pulsesensor.com](https://pulsesensor.com/), as well as
Adafruit
Sparkfun
Digikey
Mouser

Also, in some regions of the world, you can find Pulse Sensor available in brick and mortar stores, as Adafruit and Sparkfun bundle products for distribution to resellers.
