### ISSUE TITLE
Getting_BPM_to_monitor sketch displaying random values at 11250 baud

### ISSUE THREAD

**Issue by NotAvalibleLol** [WorldFamousElectronics/PulseSensorPlayground#157]
The Getting_BPM_to_monitor sketch displays random values in commas, an example would be 0,360,970.
<img width="960" alt="Screenshot 2022-10-22 184622" src="https://user-images.githubusercontent.com/99042608/197366426-268d3b18-dfa2-4601-94ed-c47a05315696.png">
Any other baud level, higher or lower, displays random characters, both on the Arduino 2.0.0 IDE and the Arduino 1.8.19 legacy version.
<img width="960" alt="Screenshot 2022-10-22 184843" src="https://user-images.githubusercontent.com/99042608/197366487-815c78e5-72c7-493c-8b78-da58fb94401f.png">
<img width="960" alt="Screenshot 2022-10-22 185031" src="https://user-images.githubusercontent.com/99042608/197366535-f8e39630-1b87-496f-94f8-3bc422d9af72.png">
I am using an Arduino UNO R3, and it is on the COM 3 port.

**Comment by biomurph** [comment]
@NotAvalibleLol 
I cannot replicate your problem on the Uno R3.
Please make sure that you upload the sketch to the Arduino, and that your baud rate is set to 9600.

**Comment by NotAvalibleLol** [comment]
Thanks for getting back to me @biomurph,

I switched to 9600 baud, but now it shows random characters.
<img width="960" alt="Screenshot 2022-10-26 182744" src="https://user-images.githubusercontent.com/99042608/198157555-cf07fb60-7c11-4d26-996d-86cacf271081.png">

**Comment by biomurph** [comment]
@NotAvalibleLol 
Something is amisss.
Are you able to program anything with serial communication that works?

**Comment by NotAvalibleLol** [comment]
No, any code that I try to put in will always have the same output, random characters.

**Comment by NotAvalibleLol** [comment]
I managed to fix it, since my sketches were not uploading properly, but now it shows very high values, upwards of 200.
<img width="957" alt="Screenshot 2022-10-30 115002" src="https://user-images.githubusercontent.com/99042608/198890879-e3f4d450-ac2a-4ac7-bf32-2a7c96f0388a.png">

**Comment by biomurph** [comment]
OK, that is something!

Now, I'm going to ask you to share a photo of the hardware setup you have.
I want to make sure you are hooked up correctly, and that your Pulse Sensor is legit. Please post a photo.

**Comment by NotAvalibleLol** [comment]
Thanks for replying!

Here is a photo of my setup, it is fairly simple. There is no LED or breadboard since I am just testing out the sketches. The Arduino UNO
![WIN_20221104_17_25_04_Pro](https://user-images.githubusercontent.com/99042608/200083789-79de4aae-543a-4804-b6a0-ba2f17cbabb6.jpg)
 is off in this photo.

**Comment by biomurph** [comment]
@NotAvalibleLol 
Thank you for sharing the photo.
It is clear from the photo that the Pulse Sensor you have is a knockoff of ours.
Since I have no idea what components are on that part, I cannot troubleshoot the problem you are having.

Please support the original makers of Pulse Sensor by purchasing only legit parts.
Our Pulse Sensor is available on our website, www.pulsesesnor.com, and distributed via Adafruit, Sparkfun, Mouser, and Digikey.
