### ISSUE TITLE
I'm getting high BPM

### ISSUE THREAD

**Issue by moja21** [WorldFamousElectronics/PulseSensorPlayground#159]
Im getting high BPM using arduino Uno + i want to use nodemcu but it doesn't show bpm

im doing the Getting_BPM_to_Monitor examble on arduino uno and the values im getting are ranging from 180 to 250
also when i try to use the nodemcu serial monitor doesn't show anything 

<img width="958" alt="Desktop Screenshot 2023 01 01 - 20 26 16 68" src="https://user-images.githubusercontent.com/113420209/210179917-c76fa8cd-8c5f-479f-89b8-e45336aca0fb.png">

![WhatsApp Image 2023-01-01 at 20 29 19](https://user-images.githubusercontent.com/113420209/210179672-503f4b89-aef8-4dd7-b11e-701e9e32a98d.jpg)

**Comment by biomurph** [comment]
@moja21 
I can see by the color shape and printing on the hardware you have that you are using a knockoff Pulse Sensor.
As I cannot know what is in the hardware piece that you are using, I cannot troubleshoot your problem.

Please support the original makers of Pulse Sensor and purchase legit parts!
