### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by joelSensor** [WorldFamousElectronics/PulseSensorPlayground#16]
The comments on the ATtiny need to be tidied up

#elif defined(__AVR_ATtiny85__)
    GTCCR &= 0x81;     // Disable PWM, don't connect pins to events
    OCR1C = 0x7C;      // Set the top of the count to  124
    OCR1A = 0x7C;      // Set the timer to interrupt after counting to 124
    #if F_CPU == 16000000L
      TCCR1 = 0x88;      // Clear Timer on Compare, Set Prescaler to 128
    #elif F_CPU == 8000000L
      TCCR1 = 0x89;      // Clear Timer on Compare, Set Prescaler to 256
    #endif
    bitSet(TIMSK,6);   // Enable interrupt on match between TCNT1 and OCR1A
    ENABLE_PULSE_SENSOR_INTERRUPTS;
    return true;

**Comment by yury-g** [comment]
believe to be resolved.
