### ISSUE TITLE
turning off/on the bright light when needed

### ISSUE THREAD

**Issue by paris007** [WorldFamousElectronics/PulseSensorPlayground#173]
I am trying to activate the data accusation in my device through a command. Hence, I was wondering how I turn the bright green light on and off on demand? is there a software-based solution to this or schematic manipulation is required?

thanks!

**Comment by paris007** [comment]
noticed that we have asked this question before

**Comment by biomurph** [comment]
@paris007 
The PulseSensor draws only about 3 to 4 milliamps, so you can drive it directly from any GPIO on pretty much any hardware platform.

Also, there are a couple of methods for controlling the activity of the PulseSensor Playground Library.
pause() and resume().
Check out the [Resources](https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/resources/PulseSensor%20Playground%20Tools.md) file in this repo for all the methods available in the library.
