### ISSUE TITLE
GETTING STARTED WORKING BUT NOT GETTING BPM TO MONITOR , ALTERNATIVE

### ISSUE THREAD

**Issue by youngsu5582** [WorldFamousElectronics/PulseSensorPlayground#177]
I try Arduino project that send heartbeat data with wifi & socket.
And , I confirm Getting StartedProject properly in sketch.
But , I use Getting_BPM_to_Monitor . pulseSensor.begin() return false

So , I use PulseSensor_BPM_Alternative sketch,
this sketch return error.

In file included from C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\src/PulseSensorPlayground.h:474,
                 from C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\examples\PulseSensor_BPM_Alternative\PulseSensor_BPM_Alternative.ino:41:
C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\src/utility/Interrupts.h: In function 'boolean PulseSensorPlaygroundDisableInterrupt()':
C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\src/utility/Interrupts.h:327:1: error: no return statement in function returning non-void [-Werror=return-type]
  327 | } // PulseSensorPlaygroundDisableInterrupt
      | ^
In file included from C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\src/PulseSensorPlayground.h:474,
                 from C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\examples\PulseSensor_BPM_Alternative\PulseSensor_BPM_Alternative.ino:41:
C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\src/utility/Interrupts.h: In function 'boolean PulseSensorPlaygroundEnableInterrupt()':
C:\Users\lphan\OneDrive\Documents\Arduino\libraries\PulseSensor_Playground\src/utility/Interrupts.h:394:1: error: no return statement in function returning non-void [-Werror=return-type]
  394 | }
      | ^

Can you teach me how to use in this case? thx you.

( Sensor : SZH-SSBH-035 )
( HW : wemos d1 esp-wroom-02 esp8266 )

**Comment by biomurph** [comment]
@youngsu5582 
That was a bug that you found! I fixed it. Please use the latest published release v1.8.2.
Now the BPM_Alternative example sketch will compile for ESP8266.
