### ISSUE TITLE
Problem about sensor when connecting with Arduino NANO 33 loT

### ISSUE THREAD

**Issue by LinkWang-web** [WorldFamousElectronics/PulseSensorPlayground#185]
Arduino NANO 33 loT sometimes causes more noise on the plotter monitor in IDE. The input value keeps weaving from 70 to 150. Adjusting the bandage of the sensor would help a bit.

**Comment by biomurph** [comment]
@LinkWang-web 
We are aware of the issue with Arduino NANO 33 platform.
Please use the PulseSensor_BPM_Alternative.ino sketch.

Could you please post a screenshot of the noise you are referring to?
Also, your OS and a picture of your PulseSensor setup?

**Comment by biomurph** [comment]
@LinkWang-web 
please switch the Playground repository branch to the 'Version-2.0-beta' branch.
Then, delete the library you have installed, and download (or fork) the Version-2.0-beta branch into your Arduino/libraries folder.
Try that and let us know how it works?

**Comment by biomurph** [comment]
This is closed because V2 solves the problem
