### ISSUE TITLE
Heart rate is abnormally high

### ISSUE THREAD

**Issue by shivanjali16rao** [WorldFamousElectronics/PulseSensorPlayground#194]
i have been using heart beat pulse sensor. No matter what, heart beat is over 200

**Comment by biomurph** [comment]
@nammoorigebanni68 
Sorry to hear you are having this problem.
Please give us more information so that we can troubleshoot your problem.
What OS are you using?
What microcontroller board are you using?
What code, or  example are you using?
Please also drop in a photo of your setup, so that we can understand your use case better.

**Comment by shivanjali16rao** [comment]
> @nammoorigebanni68 Sorry to hear you are having this problem. Please give us more information so that we can troubleshoot your problem. What OS are you using? What microcontroller board are you using? What code, or example are you using? Please also drop in a photo of your setup, so that we can understand your use case better.

hey! 
os - windows 11
microcontroller- arduino uno r3
code - pulsesensorplayground example - getting bpm on monitor
I don't have the actual photo of connections, I will attach the reference we used

![image](https://github.com/WorldFamousElectronics/PulseSensorPlayground/assets/156174074/dd9ccf41-2af6-43b0-9d6c-2ff578709f9e)

**Comment by biomurph** [comment]
@shivanjali16rao 
Our code examples work with the Arduino UNO R3 very well.
Please send a photo of your hardware setup? Or a link to the PulseSensor that you bought?

**Comment by biomurph** [comment]
@shivanjali16rao 
Please reply with a photo of your PulseSensor setup so that I can help you troubleshoot.
If I don't hear from you by August, I will have to close this issue.

**Comment by biomurph** [comment]
This issue is closed due to non-response.
