### ISSUE TITLE
BPM is 150+

### ISSUE THREAD

**Issue by eomsanghyun** [WorldFamousElectronics/PulseSensorPlayground#20]
I use BPM alternative source code on arduino 101(intel curie) board.
BPM is not stable...
![image](https://user-images.githubusercontent.com/20294358/30576286-ce7d3d68-9d41-11e7-9d2b-706c1e3fcb19.png)
What is problem??
I want stable value. Please help me.. :(

**Comment by joelSensor** [comment]
Please let me know what example sketch you are using?

**Comment by yury-g** [comment]
eomsanghyun,

Yes, the PulseSensor works with the Arduino 101.  We just created a Playground Library, with lots of projects already coded. 
**Once you've installed our new Library:** 
https://github.com/WorldFamousElectronics/PulseSensorPlayground/


**Check-out the Example titled:  "PulseSensor_BPM_Alternative"**

![examplepath](https://user-images.githubusercontent.com/12190048/34799644-9723a94c-f62e-11e7-963b-7283653c01fd.png)
