### ISSUE TITLE
Is there a way to simply get a numeric BPM

### ISSUE THREAD

**Issue by SparkMike77** [WorldFamousElectronics/PulseSensorPlayground#29]
I'm looking for how to just pull the BPM number, not plot it on a graph but all the BPM sketches have a graphing output.

I'm assuming instead of calling pulseSensor.outputBeat() there's a way just to call for the numeric BPM?

**Comment by joelSensor** [comment]
There is a way to just get BPM number.
Please check out the PulseSensor Playground Tools
https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/resources/PulseSenaor%20Playground%20Tools.md

a call to getBeatsPerMinute() will return the latest BPM value (int). You can simply comment out the call to pulseSensor.outputBeat() and just do you own thing instead.

**Comment by yury-g** [comment]
SparkMike77, 
I drafted some code here for you.  It's not pretty, but it does the behavior you requested. 
Try this code in a new Sketch, or just run it as an ".ino" file in Arduino. 
[https://github.com/yury-g/ReadMePlayground/blob/master/PulseSensor_BPM_Serial_Print.ino](https://github.com/yury-g/ReadMePlayground/blob/master/PulseSensor_BPM_Serial_Print.ino
)

This is a screengrab of it working correctly: 
Let me know if it helps!
<img width="818" alt="pulsesensor_bpm_code_screengrab" src="https://user-images.githubusercontent.com/12190048/34799068-51df46cc-f62c-11e7-9d0c-dc9bacc25404.png">

**Comment by yury-g** [comment]
Mike, 
Try the sketch at this link. It is BPM and BPM-only via our new Library.  ; ) 

https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/examples/Getting_BPM_to_Monitor/Getting_BPM_to_Monitor

**Comment by SparkMike77** [comment]
Thanks Guys, I had completely forgotten to check back and was hammering on my own library (really poorly).  This looks exactly like what I need!

**Comment by haarers** [comment]
Is there somewhere that I can see the code for the function

getBeatsPerMinute()

Thanks!

**Comment by biomurph** [comment]
The actual function is pretty simple, and it's on line 87 here
https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/src/utility/PulseSensor.cpp

The function that determines BPM is called processLatestSample, on line 122 of the same file.

**Comment by haarers** [comment]
Thank you, Joel.   I appreciate this.    -Shawn Haarer
