### ISSUE TITLE
PulseSensorPlayground does not work on Arduino Mega 2650

### ISSUE THREAD

**Issue by Williamvdb** [WorldFamousElectronics/PulseSensorPlayground#45]
I am using your example sketch called Getting_BPM_to_Monitor, it works on my Arduino UNO, but not on my Arduino Mega 2560. Why is that? 

It does not even Serial print "We created a pulseSensor Object!" indicating that pulseSensor.begin() failed. The Serial Monitor is completely empty.

**Comment by biomurph** [comment]
We don't yet support use of interrupts on the Mega. You will need to run the BPM_Alternative code example. If all you want is BPM on the serial port, then you will need to add a variable at the top of the sketch 

`int myBPM;`

Then modify part of the code in the loop to be something like this

`if (pulseSensor.sawStartOfBeat()) {
        myBPM = pulsesensor.getBeatsPerMinute();
        Serial.print("BPM: ");
        Serial.println(myBPM);
      }`

**Comment by bhavindave9** [comment]
so can we expect the support for Mega anytime soon? would love to get my hand dirty on.

**Comment by bhavindave9** [comment]
I checked the arduino mega 2560 data sheet .Everything (timer section that we are using) is same as uno.
so what is the problem here? how we can use this existing code on mega using interrupts . would really appreciate if you can help .

**Comment by biomurph** [comment]
Thanks for your encouragement re the mega!
We are working to expand the boards that can use interrupts. Right now, you can get good sample timing with the BPM_Alternative example. If you need tight sample timing, you can try the old interrupt code found here
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino
It targers the same timer as the UNO. Give it a shot and let us know what happens. We will take your results and mod our playground library

**Comment by bhavindave9** [comment]
I will definitely try it and will let you know the results

**Comment by chumvan** [comment]
I have the same issue, did you fix this?

  If I set `#define USE_ARDUINO_INTERRUPTS true` :
  I can run the program without error but it return nothing on the monitor and plotter

  If I set `#define USE_ARDUINO_INTERRUPTS false` :
  The program just return straight lines which means it can not measure anything.

I tried to return raw value from the sensor, it was fine so there is no problem with the sensor.
If I want to use functions in PulseSensorPlayground.h to get BPM, how should I do it? I tried to figure something in PulseSensorPlayground.h and PulseSensorPlayground.cpp but it's too hard for me.

**Comment by biomurph** [comment]
I think I have a mega2650around here somewhere. I'll see if I can replicate your problem.

**Comment by luto65** [comment]
I have also a MEGA and still having the same problem

**Comment by biomurph** [comment]
I will be able to fix the issue this week.

**Comment by biomurph** [comment]
@luto65 @VANHUUTHANHTRUNG @bhavindave9 

The latest release of PulseSensor Playground supports Arduino MEGA boards. Please let us know if you run into any bugs. I've tested it with and without including the Servo library, though have not used with servo on MEGA. 
You can update your library through the Arduino Library manager. Latest is version 1.4.13

**Comment by luto65** [comment]
I tried it today and unfortunately does not work still.
<img width="1144" alt="Bildschirmfoto 2019-05-05 um 21 38 22" src="https://user-images.githubusercontent.com/2243367/57199491-c0f01500-6f7f-11e9-94b5-d10eb422b35b.png"> as you can see here the green line (the sensor) does not change ...
