### ISSUE TITLE
error “unexpectedtoken:def” in Processing

### ISSUE THREAD

**Issue by georod99** [WorldFamousElectronics/PulseSensorPlayground#47]
Antecedents.
1.	I’m receiving biofeedback therapy from an specialist and I should like to replicate his equipment so I can practice at home.
2.	He uses the Bio-Trace Nexus 10, very expensive ($5,000).
3.	The therapy sessions consist of:
a.	He attaches to me a breathing strap, two skin galvanic electrodes, one thermistor and a Blood Volume Pulse (BVP), (photoplethysmograph).
b.	Then I watch a breathing pacer and follow the breathing pattern of 6 breaths per minute for several minutes. This is the rate that is considered best to increase one’s HRV.
c.	After that I try to continue breathing at that rate, and watch the graph of my HRV, and try (subconsciously) to increase the HRV.
d.	His system records many variables, but temperature and galvanic response remain very much constant. The main part is the curve of the heart beats and how they go up and down with the breathing, and the HRV bar (that is the same thing).
4.	Other devices (phone aps) only measure HRV during several minutes, and then give the values of RMSSD, SDNN, SDANN, LF, HF, HF/LF, (from the Fourier Transforms) and Poincare plot.
5.	Most people do not understand this, and they are presented with a value that is the average over several minutes.
6.	All these applications are aimed at training and give advice as to your state of recuperation from exercise.
7.	So, I bought a PulseSensor and an Arduino. I spent the following two months studying and practicing with some Arduino projects.
8.	I assisted several times to an Arduino group in my city, but I have reached a point that I need help.
What I have done:
1.	Run the PulseSensor_BMP and I obtain the tree curves. No problem so far.
2.	Download Processing and copied the code from Arduino IDE to Processing, changing the const int OUTPUT_TYPE = SERIAL_PLOTTER; to PROCESSING_VISUALIZER.
3.	This is the code:
4.	#define USE_ARDUINO_INTERRUPTS true
5.	#include <PulseSensorPlayground.h>
6.	
7.	/*
8.	   The format of our output.
9.	
10.	   Set this to PROCESSING_VISUALIZER if you're going to run
11.	    the Processing Visualizer Sketch.
12.	    See https://github.com/WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer
13.	
14.	   Set this to SERIAL_PLOTTER if you're going to run
15.	    the Arduino IDE's Serial Plotter.
16.	*/
17.	const int OUTPUT_TYPE = PROCESSING_VISUALIZER;
18.	
19.	/*
20.	   Pinout:
21.	     PIN_INPUT = Analog Input. Connected to the pulse sensor
22.	      purple (signal) wire.
23.	     PIN_BLINK = digital Output. Connected to an LED (and 220 ohm resistor)
24.	      that will flash on each detected pulse.
25.	     PIN_FADE = digital Output. PWM pin onnected to an LED (and resistor)
26.	      that will smoothly fade with each pulse.
27.	      NOTE: PIN_FADE must be a pin that supports PWM. Do not use
28.	      pin 9 or 10, because those pins' PWM interferes with the sample timer.
29.	*/
30.	const int PIN_INPUT = A0;
31.	const int PIN_BLINK = 13;    // Pin 13 is the on-board LED
32.	const int PIN_FADE = 5;
33.	const int THRESHOLD = 550;   // Adjust this number to avoid noise when idle
34.	
35.	/*
36.	   All the PulseSensor Playground functions.
37.	*/
38.	PulseSensorPlayground pulseSensor;
39.	
40.	void setup() {
41.	  /*
42.	     Use 115200 baud because that's what the Processing Sketch expects to read,
43.	     and because that speed provides about 11 bytes per millisecond.
44.	
45.	     If we used a slower baud rate, we'd likely write bytes faster than
46.	     they can be transmitted, which would mess up the timing
47.	     of readSensor() calls, which would make the pulse measurement
48.	     not work properly.
49.	  */
50.	  Serial.begin(115200);
51.	
52.	  // Configure the PulseSensor manager.
53.	
54.	  pulseSensor.analogInput(PIN_INPUT);
55.	  pulseSensor.blinkOnPulse(PIN_BLINK);
56.	  pulseSensor.fadeOnPulse(PIN_FADE);
57.	
58.	  pulseSensor.setSerial(Serial);
59.	  pulseSensor.setOutputType(OUTPUT_TYPE);
60.	  pulseSensor.setThreshold(THRESHOLD);
61.	
62.	  // Now that everything is ready, start reading the PulseSensor signal.
63.	  if (!pulseSensor.begin()) {
64.	    /*
65.	       PulseSensor initialization failed,
66.	       likely because our particular Arduino platform interrupts
67.	       aren't supported yet.
68.	
69.	       If your Sketch hangs here, try ProcessEverySample.ino,
70.	       which doesn't use interrupts.
71.	    */
72.	    for(;;) {
73.	      // Flash the led to show things didn't work.
74.	      digitalWrite(PIN_BLINK, LOW);
75.	      delay(50);
76.	      digitalWrite(PIN_BLINK, HIGH);
77.	      delay(50);
78.	    }
79.	  }
80.	}
81.	
82.	void loop() {
83.	  /*
84.	     Wait a bit.
85.	     We don't output every sample, because our baud rate
86.	     won't support that much I/O.
87.	  */
88.	  delay(20);
89.	
90.	  // write the latest sample to Serial.
91.	 pulseSensor.outputSample();
92.	
93.	  /*
94.	     If a beat has happened since we last checked,
95.	     write the per-beat information to Serial.
96.	   */
97.	  if (pulseSensor.sawStartOfBeat()) {
98.	   pulseSensor.outputBeat();
99.	  }
100.	}

When I run the sketch, I obtain the error “unexpectedtoken:def” and the program stops at: #define USE_ARDUINO_INTERRUPTS true.
Remember: This is Processing.
Any suggestion?
I will post now another question under another subject.

**Comment by biomurph** [comment]
@georod99 
It sounds like you are on the right track to create a low cost HRV tracker.
Just to clarify, the Arduino sketch you should use is the one found here
https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/examples/PulseSensor_BPM/PulseSensor_BPM.ino
PulseSensor_BPM is listed in the examples drop down under PulseSensor Playground in the Arduino IDE. 
The processing sketch is found here
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer
And that sketch should be run in the Processing IDE, downloaded from www.processing.org.

You should know That we have our own HRV visualization sketches written in Processing. Please follow the tutorial here
https://pulsesensor.com/pages/hrv-poincare-plot
It will guide you through a Poincare plot, Time domain plot, and a simple Frequency plotter. The Time domain plot would be the one that I think would be most useful for you to use if you want to watch how the HRV changes with your breath.

Are you running the Arduino code in the Processing IDE?
