### ISSUE TITLE
Pulse sensor with multiple coonections.

### ISSUE THREAD

**Issue by bhavindave9** [WorldFamousElectronics/PulseSensorPlayground#49]
Hey,
Absolutely loved your product. I am currently building a project where we can detect bmp, display it on the LCD as well as send the data to the clouds via wifi module.

As the whole process is i.e detecting heartbeat, processing it, displaying it on LCD as well sending that data to the servers is generating a lot of delays. and due to which it is generating a lot of irregular bpm readings.
As uno have only serial communication line, I Tried using mega 2560 which allows me to use 2 separate baud rates (which I think can help me to get better results). but for now, pulseSensor library does not support Arduino mega 2560.

So to tackle this I am planning to use two Arduino (uno,mega) and connect them via i2c?
uno will detect the bpm and display it on LCD and mega will send that bmp to the servers.

So can you tell me is this idea viable? can this work and if not, what else do I need to do?
your input is highly appreciated.

would love to share the details of my work once completed.

**Comment by biomurph** [comment]
You can do that, I think.
You can also use the mega, but you won't be using interrupts. It should still be pretty accurate.
