### ISSUE TITLE
Other methods of calculating BPM

### ISSUE THREAD

**Issue by NovaBringer** [WorldFamousElectronics/PulseSensorPlayground#50]
Hey, I was wondering if there is another way of calculating a person's BPM without using the pulse sensor library. I know that you have to read the sensor, but I do not know how to continue after this.

**Comment by biomurph** [comment]
The way to determine BPM is to first find the 'moment of heart beat'. Then, you need to measure time between that and the next 'moment of heart beat'. It is important to be as accurate as possible in the timing to get an accurate BPM. Please refer to this document for more information The code it discusses is superseded by the Pulse Sensor Library, but it has useful information. It has some links at the end for further reading.

https://pulsesensor.com/pages/pulse-sensor-amped-arduino-v1dot1
