### ISSUE TITLE
Display BPM only one time!

### ISSUE THREAD

**Issue by HoangTanPhat** [WorldFamousElectronics/PulseSensorPlayground#51]
Hi! I'm doing a project with a pulse sensor, I'm new to arduino too and i got some proplems. Is there anyway to just send 20 first BPM value to serial (to get the stable value) and display the 20th BPM to LCD  (just display 1 time)? Or get the BPM just in 10 seconds, display the BPM that appear oftenly and then stop? All i need is just get 1 BPM value when i think it's stable . How can I do that?
Thanks for reading this! Sorry for my bad English.

**Comment by biomurph** [comment]
Well, it would help if you shared a link to your code, but it should be easy to average a number of BPM values (10 or 20 or whatever) and when you reach that number of BPMs, then print to the LCD.
