### ISSUE TITLE
Errors in compiling the library for Adafruit Feather M0

### ISSUE THREAD

**Issue by jamierajewski** [WorldFamousElectronics/PulseSensorPlayground#52]
I'm trying to use the pulse sensor library with an Adafruit Feather M0 but there are various issues when compiling; I have attached the error output from Arduino IDE.
[Errors.txt](https://github.com/WorldFamousElectronics/PulseSensorPlayground/files/2002688/Errors.txt)

**Comment by biomurph** [comment]
@ejams 
I have encountered this type of error before. Something about the cli() and sei() functions not being defined for the Feather. Need to carve out a case for it. I have a feather nearby, and will test a fix for this and get back on this issue.

**Comment by biomurph** [comment]
@ejams 
I think I fixed it, but I don't actually have a Feather M0. I have a Feather ESP...
I did adjust the code to accommodate the M0, and I think it works. 
At least it compiles :)
Please download the Playground library from this repo into your Arduino/libraries folder, and then give it a shot. You should use the BPM_Alternative example. Let me know how it goes.

**Comment by jamierajewski** [comment]
@biomurph I don't actually have access to the Feather M0 I was using anymore as I was on a tight schedule and completed the project with an Uno instead. It sounds like you fixed it though, so you can probably close the issue now but I appreciate the quick action to get it working and I'll give it a shot in the future if I get a chance :+1:
