### ISSUE TITLE
What is the most accurate method for calculating BPM within a duration of 10s

### ISSUE THREAD

**Issue by NovaBringer** [WorldFamousElectronics/PulseSensorPlayground#53]
So I want to calculate the BPM of many people within a duration of 10s, and I do not want to constantly adjust the threshold. 

Would the best way be using the PulseSensor library and doing something as simple as:
```
while (millis() - startTime < 10000)
  {
    int BPM = pulseSensor.getBeatsPerMinute(); 
  }
```
Then the BPM of the person will be the value of the BPM variable after the while loop is completed?

**Comment by biomurph** [comment]
If you just want to get the BPM value after 10 seconds, then you should do something like

int BPM;

setup(){
// other stuff
startTime = millis();
}

loop(){
// other stuff
if(millis() - startTime > 10000){
  BPM = pulseSensor.getBeatsPerMinute();
  startTime = millis();
}

declaring BPM as a global variable makes it possible to use it outside of the if statement.

**Comment by NovaBringer** [comment]
How accurate is the getBeatsPerMinute function, since you aren't using a defined threshold like 550.

**Comment by biomurph** [comment]
The BPM is accurate to 2 milliseconds.

**Comment by NovaBringer** [comment]
Oh, sorry. What I meant was how does the getBeatsPerMinute function work, and how accurate is it in detecting the beats?

**Comment by biomurph** [comment]
The algorithm will consider an upward-going pulse wave signal if it crosses the threshold variable, and as long as it happens after 3/5ths of the last IBI (inter-beat-interval). That time is there to avoid any noise or 'dichrotic notch' in the signal.

Most research that I have seen says that the 'moment of heart beat' in the PPG signal happens at the point of the steepest slope of the pulse wave. That also corresponds to just about the middle of the upward going pulse wave. PulseSensor Playground will measure the amplitude of the pulse wave, so you can also use that to 'tune' the threshold at 1/2 the amplitude. We don't have that code on offer yet, but it should be fairly straightforward to implement. Just be sure to give yourself lots of serial feedback, so you can follow how well it's working.

**Comment by NovaBringer** [comment]
Alright, and is it more accurate then if you are doing a more manual method? 

Something like: 

```
#define sensor A0
byte BPM;
unsigned long startTime;
const int threshold = 550;

void setup()
{
}

void loop()
{
    startTime = millis();
    while (millis() - startTime > 10000)
    {
        if (analogRead(sensor) > threshold)
            BPM++;
    }
    BPM = BPM * 6;
}
```

or

1) Find the time when each "heartbeat" occur in 10s (When the reading crosses the threshold) and store into an array
2) Find the Interbeat Intervals (Time difference between each "heartbeat") and store into another array
3) Find the median value from the Interbeat Intervals array
4) Filter the Interbeat Intervals array by comparing it with the median.
If a value in the Interbeat Interval array is within 80% of the median, add it into a 3rd array
5) From the 3rd array, find the average
6) Find the BPM, BPM = 60000/average (60000 since we are measuring within a timespan of 10s)

**Comment by biomurph** [comment]
Well, you could do that I suppose.
In order to get IBI, you need accurate sample timing, which your example doesn't do. That's why we use timer interrupts whenever we can.
Every time we sense a pulse, we calculate IBI, and also the instantaneous BPM.

**Comment by NovaBringer** [comment]
Regarding the getBeatsPerMinute function, how does it compute the value of the BPM? What if instead of 10s in my example, the time is only 0.5s, and it only detects 1 beat. What will be the value of the BPM then? Likewise, what if during the duration of 10s, the heartrate slowly increases. Will it show the BPM of the last beat, or does it take the average of the beats during the 10s?

**Comment by biomurph** [comment]
The function that calculates BPM uses a rolling average of the previous 10 beats. When a new beat happens, the oldest beat is thrown out and a new average is made of the new beat plus the previous 9 beats.
