### ISSUE TITLE
Connect PulseSensor to nRF51822

### ISSUE THREAD

**Issue by francesco98** [WorldFamousElectronics/PulseSensorPlayground#63]
Hi,

I want to connect the Pulse Sensor to nRF51822. Is it possible?

Thank you

**Comment by biomurph** [comment]
I have not used the nRF51822 directly, however I have used the [Simblee](https://www.simblee.com/) and [RFduino](http://www.rfduino.com/) made by RFDigital (now bought up by someone else). Both of those are built on the nRF51822 glass. There should be no problem connecting the Pulse Sensor to one of the analog pins. You will likely want to use the BPM_Alternative code example if you are going to run BLE or Gazelle stack, as the radio will stomp on your interrupts (in my experience). I don't see any issue with using either BLE or Gazelle to send the data over air. What you will have to do is buffer the samples (BLE allows 20 bytes per radio packet, Gazelle allows 32 bytes per radio packet). Pulse Sensor samples at 500Hz, 2mS, so you should be fine if you collect samples to fill the packet, and then send over air. On the other side, you will have to unpack, but that's trivial.

**Comment by francesco98** [comment]
Thanks for your support. I'm using the alternative code, but I'm receiving these errors:
- `error: 'cli' was not declared in this scope`
- `error: 'sei' was not declared in this scope`

How can I resolve? Thanks.

**Comment by biomurph** [comment]
Ah, ok. Are you using the Arduino IDE? If so, what board are you targeting?

**Comment by francesco98** [comment]
The target is: **Generic nRF1**

**Comment by biomurph** [comment]
Can you link me to the json for the board cores?

**Comment by francesco98** [comment]
Where can I find it? I'm using this: [https://github.com/sandeepmistry/arduino-nRF5](https://github.com/sandeepmistry/arduino-nRF5)

**Comment by biomurph** [comment]
OK, I just added support for the nRF5 architecture.
Please download the library from this repo, and replace the one you have in your libraries folder.
I don't have any nRF boards in house, but it does compile on my machine.

LMK if you get it to work on your board.

**Comment by francesco98** [comment]
Ok thanks, but I have another problem..
I'm connecting the pulse sensor to ATTiny85, but I'm receiving this error:
`PulseSensorPlayground.cpp:28: undefined reference to `operator new[](unsigned int)'`

Sorry for my many question..

**Comment by biomurph** [comment]
That seems a strange error. I am able to compile targeting a Gemma board. What board are you using?
ATTiny85 don't have any hardware serial port, so you need to use the Software Serial Demo example code to get started.

**Comment by francesco98** [comment]
I have solved by replacing `new PulseSensor[SensorCount]` with `(PulseSensor*) malloc(SensorCount * sizeof(PulseSensor))`

**Comment by biomurph** [comment]
Great! We'll look into rolling that change in the next release.
