### ISSUE TITLE
BPM won't go back to zero and blink pin and fade pin do not turn on although BPM is not zero

### ISSUE THREAD

**Issue by stevekn** [WorldFamousElectronics/PulseSensorPlayground#67]
I am making  a remote heart rate monitor to send BPM to an android phone. The android part works correctly. However, the BPM fails to go back to zero after I remove the finger. With the finger placed on the sensor, the system works well and the blink and fade pins work nicely as well. However, upon removing the finger, the blink pin and fade pin remain off but the BPM sent through serial is not zero. At times, pressing the return button returns BPM to zero. However, I expected that if the BPM is not zero, the blink pin should be blinking. My code pasted below;

/*
   Code to detect pulses from the PulseSensor,
   using an interrupt service routine.

   Here is a link to the tutorial\
   https://pulsesensor.com/pages/getting-advanced

   Copyright World Famous Electronics LLC - see LICENSE
   Contributors:
     Joel Murphy, https://pulsesensor.com
     Yury Gitman, https://pulsesensor.com
     Bradford Needham, @bneedhamia, https://bluepapertech.com

   Licensed under the MIT License, a copy of which
   should have been included with this software.

   This software is not intended for medical use.
*/

/*
   Every Sketch that uses the PulseSensor Playground must
   define USE_ARDUINO_INTERRUPTS before including PulseSensorPlayground.h.
   Here, #define USE_ARDUINO_INTERRUPTS true tells the library to use
   interrupts to automatically read and process PulseSensor data.

   See ProcessEverySample.ino for an example of not using interrupts.
*/
#define USE_ARDUINO_INTERRUPTS true
#include <SoftwareSerial.h>
#include <PulseSensorPlayground.h>

/*
   The format of our output.

   Set this to PROCESSING_VISUALIZER if you're going to run
    the Processing Visualizer Sketch.
    See https://github.com/WorldFamousElectronics/PulseSensor_Amped_Processing_Visualizer

   Set this to SERIAL_PLOTTER if you're going to run
    the Arduino IDE's Serial Plotter.
*/
const int OUTPUT_TYPE = SERIAL_PLOTTER;

/*
   Pinout:
     PIN_INPUT = Analog Input. Connected to the pulse sensor
      purple (signal) wire.
     PIN_BLINK = digital Output. Connected to an LED (and 220 ohm resistor)
      that will flash on each detected pulse.
     PIN_FADE = digital Output. PWM pin onnected to an LED (and resistor)
      that will smoothly fade with each pulse.
      NOTE: PIN_FADE must be a pin that supports PWM. Do not use
      pin 9 or 10, because those pins' PWM interferes with the sample timer.
*/
const int BT_RX = 3;
const int BT_TX = 4;
const int PIN_INPUT = A2;
const int PIN_BLINK = 13;    // Pin 13 is the on-board LED
const int PIN_FADE = 6;
const int ALERT_PIN=10;
const int buzzer=5;
const int THRESHOLD = 550;   // Adjust this number to avoid noise when idle
int period = 100; //time to wait before printing via BT
int period2=500; //time to play alert sound and light up alert
int period3=20; // time for outputiing data to serial
unsigned long time_now = 0;// used sith period for millis timer
/*
   All the PulseSensor Playground functions.
*/
PulseSensorPlayground pulseSensor;
SoftwareSerial BTSerial(BT_RX, BT_TX);

void setup() {
  /*
     Use 115200 baud because that's what the Processing Sketch expects to read,
     and because that speed provides about 11 bytes per millisecond.

     If we used a slower baud rate, we'd likely write bytes faster than
     they can be transmitted, which would mess up the timing
     of readSensor() calls, which would make the pulse measurement
     not work properly.
  */
  Serial.begin(115200);
  BTSerial.begin (9600);
  pinMode (ALERT_PIN, OUTPUT);
  pinMode (buzzer, OUTPUT);

  // Configure the PulseSensor manager.

  pulseSensor.analogInput(PIN_INPUT);
  pulseSensor.blinkOnPulse(PIN_BLINK);
  pulseSensor.fadeOnPulse(PIN_FADE);

  pulseSensor.setSerial(Serial);
  pulseSensor.setOutputType(OUTPUT_TYPE);
  pulseSensor.setThreshold(THRESHOLD);

  // Now that everything is ready, start reading the PulseSensor signal.
  if (!pulseSensor.begin()) {
    /*
       PulseSensor initialization failed,
       likely because our particular Arduino platform interrupts
       aren't supported yet.

       If your Sketch hangs here, try ProcessEverySample.ino,
       which doesn't use interrupts.
    */
    for(;;) {
      // Flash the led to show things didn't work.
      digitalWrite(PIN_BLINK, LOW);
      delay(50);
      digitalWrite(PIN_BLINK, HIGH);
      delay(50);
    }
  }
}

void loop() {
  
    int myBPM=pulseSensor.getBeatsPerMinute ();
   if (myBPM>100){
        time_now = millis();
        tone(buzzer, 1000); // Send 1KHz sound signal...
        digitalWrite (ALERT_PIN, HIGH);
        while(millis() < time_now + period2);
     
        }
     else if (myBPM<60){
        time_now = millis();
        tone(buzzer, 1000); // Send 1KHz sound signal...
        digitalWrite (ALERT_PIN, HIGH);
        while(millis() < time_now + period2);
     
        }
     else {
        noTone (buzzer);
        digitalWrite (ALERT_PIN, LOW);
        }

  /*
     Wait a bit.
     We don't output every sample, because our baud rate
     won't support that much I/O.
  */
  if (millis() > time_now + period3){
     time_now = millis();

     // write the latest sample to Serial.
     pulseSensor.outputSample();

      /*
     If a beat has happened since we last checked,
     write the per-beat information to Serial.
    */
    if (pulseSensor.sawStartOfBeat()) {
        pulseSensor.outputBeat();
        }
    }
  if (millis() > time_now + period){
     time_now = millis();
     BTSerial.println(pulseSensor.getBeatsPerMinute());
        
    }
  
}

**Comment by biomurph** [comment]
The BPM not going to zero happens because the BPM variable did not get reset by the library. This is fixed in the 1.4.11 Playground release.
The reason that the LEDs aren't lighting is because they only light when the library finds a beat. When no finger is there, there is not beat, so no LED.
Please try downloading the latest Library release (or use the Arduino Libraries Manager) and see if that helps.

**Comment by yury-g** [comment]
Thanks for using our PulseSensor Library for the latest software releases.  [https://www.youtube.com/watch?v=Pt0fJvIeryY](https://www.youtube.com/watch?v=Pt0fJvIeryY)
