### ISSUE TITLE
How to display only bpm value on Nucleo 64 board?

### ISSUE THREAD

**Issue by Teeblackgold97** [WorldFamousElectronics/PulseSensorPlayground#75]
Hi, 

I tried some examples from Pulsesensor Playground, from the Pulsesensor_Nucleo, how can I display only BPM values on serial monitor? I tried the Pulsesensor_BPM and Getting_BPM_to_monitor, both yielded no result. 

OS: Windows 10
Software used: Arduino v18.8

**Comment by biomurph** [comment]
@Teeblackgold97 
The PulseSensor_BPM and the Getting_BPM_to_Monitor both use interrupts.
We don't support interrupts on the Nucleo yet.
To only get the BPM printed to the serial port, us the PulseSensor_Nucleo sketch and replace the line

`pulseSensor.outputBeat();`
with the line
`Serial.println(pulseSensor.getBeatsPerMinute());`

That will only print the BPM to the serial monitor.
There's lots of other user functions in the [PulseSensor Playground Tools](https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/resources/PulseSensor%20Playground%20Tools.md) page.
