### ISSUE TITLE
Not working with Beetle Bluno

### ISSUE THREAD

**Issue by Virgilius1995** [WorldFamousElectronics/PulseSensorPlayground#77]
I've tried a couple of versions of your playground as well as switching between A0 and A1 and varying the threshold between 10 and 1024 without any luck. Any ideas?

**Comment by biomurph** [comment]
Can you give me some more details about what you mean by 'not working'?
Also, send a pick of your pulsesensor do hardware setup.

**Comment by Virgilius1995** [comment]
Since none of the code I could find is working, I've setup a simple script to test the signal for consistent fluctuation with the sensor connected to my finger(also had some other people try):

const int inputPin = A1;
const int threshold = 12;

void setup() {

  Serial.begin(115200);
}

void loop() {

  int signal = (analogRead(inputPin));

  if (signal > threshold)
  {
    Serial.println(signal * 5);
  }

  delay(1);
  Serial.println(10);
}

I've set the script to only plot when the input is higher than 12(since below 12 I get allot of noise). According to the provided documentation the threshold should be between 1 and 1024 but anything above twelve and I get nothing and anything below is just noise.

![o5u3ey_d3vu8knabhtbnjvu5rplac5_szw](https://user-images.githubusercontent.com/32931869/52471593-edbba880-2b99-11e9-9e13-1d78b3761725.png)
![b6golyfpfgxkseqsiswzigl2ntuqshsgpw](https://user-images.githubusercontent.com/32931869/52471628-0035e200-2b9a-11e9-974d-e666fca475bd.png)

**Comment by Virgilius1995** [comment]
I should add that I doubt the authenticity of my sensor since the wires it came solder with are the wrong color
![img_20190207_080740 1](https://user-images.githubusercontent.com/32931869/52471740-3d01d900-2b9a-11e9-9eec-7889030bac0e.jpg)
![heart-rate-pulse-sensor](https://user-images.githubusercontent.com/32931869/52471749-412df680-2b9a-11e9-94c4-4437d76925ec.jpg)

**Comment by biomurph** [comment]
It does appear that you are using a counterfeit Pulse Sensor.
I'm sorry, but I can't troubleshoot your problem since I have no idea what the hardware is.

Please support original makers by purchasing legit parts from reliable suppliers
www.pulsesensor.com
www.adafruit.com
www.sparkfun.com
[digikey](https://www.digikey.com/products/en/maker-diy-educational/gadgets-gizmos/941?k=pulse%20sensor)
[mouser](https://www.mouser.com/Sensors/Sensor-Development-Tools/_/N-d0qxl?Keyword=pulsesensor&FS=True)
[Amazon](https://www.amazon.com/PulseSensor-com-Original-Pulse-Sensor-project/dp/B01CPP4QM0/ref=sr_1_1?keywords=pulsesensor&qid=1549914583&s=gateway&sr=8-1-spell)

**Comment by Virgilius1995** [comment]
Thanks for the info 
I was told it was an original and I'll be in contact with the seller.

**Comment by biomurph** [comment]
Oh, interesting!
Please let me know the name of the seller?

**Comment by Virgilius1995** [comment]
They've came back to me saying it was possibly a third party release... And they've sent me a replacement as well as saying they're going to make a note on the product. Its a bit difficult for me to order from official sites as I live in South Africa. The site is DIYElectronics... But going back I cant find anywhere indicating it to be original, except for original images being used to advertised and the link to the official site.

**Comment by biomurph** [comment]
SparkFun bundles products from their store an ships them to brick and mortar stores all over the world.
Check out their distributors page
https://www.sparkfun.com/distributors
There are some locations in South Africa that they supply. Might have Pulse Sensor and other cool stuff
