### ISSUE TITLE
Understanding output values

### ISSUE THREAD

**Issue by shadrak98** [WorldFamousElectronics/PulseSensorPlayground#89]
on line 153 in examples/PulseSensor_BPM_alternative my serial monitar is printing 3 values separated by comma which among them is original heartbeat value

**Comment by biomurph** [comment]
@shadrak98 
The output to serial monitor is in order
**BPM, IBI, Signal**
With a carriage return at the end. This is digestible by the Arduino Serial Plotter, and you can see in that window when it's running the color of the data plots is in order at the top right.

If you just want one or more of the values, check out the [PulseSensor Playground Toolbox](https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/resources/PulseSensor%20Playground%20Tools.md)

You call these functions and get the values returned from them

### getLatestSample()
Returns the most recently read analog value from the Pulse Sensor. Type = int.

---
### getBeatsPerMinute()
Returns the latest beats-per-minute. Type = int.

---
### getInterBeatIntervalMs()
Returns the latest inter-beat interval (IBI) in milliseconds. Type = int.
