### ISSUE TITLE
Hello, I have a problem, please help me.

### ISSUE THREAD

**Issue by gyubinoh** [WorldFamousElectronics/PulseSensorPlayground#98]
Hello. I want to see the BPM on the OLED(SSD1306).
But I have problems, There are errer messages.
What can I do? please help me,
 
C:\Users\13Z940\AppData\Local\Temp\ccbjC5JN.ltrans1.ltrans.o: In function `begin':

C:\Users\13Z940\Documents\Arduino\libraries\PulseSensorPlayground-master\src/PulseSensorPlayground.cpp:56: undefined reference to `PulseSensorPlayground::UsingInterrupts'

C:\Users\13Z940\Documents\Arduino\libraries\PulseSensorPlayground-master\src/PulseSensorPlayground.cpp:57: undefined reference to `PulseSensorPlaygroundSetupInterrupt()'

collect2.exe: error: ld returned 1 exit status

exit status 1

**Comment by biomurph** [comment]
@gyubinoh 
In order to help you troubleshoot, I need more information.
What hardware platform are you targeting?
What code are you using? 
Can you get Pulse Sensor to work alone, without the OLED?
